# Generated by Django 4.2.9 on 2024-03-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assay',
            old_name='feeder_name',
            new_name='feeder_num',
        ),
    ]
