# Generated by Django 4.2.9 on 2024-03-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_feeder_name_assay_feeder_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_name', models.CharField(max_length=50)),
                ('job_number', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.RenameField(
            model_name='residencecard',
            old_name='Residence_img',
            new_name='residence_img',
        ),
    ]
