# Generated by Django 4.2.9 on 2024-03-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_usertable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='user_role',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
