# Generated by Django 4.2.9 on 2024-03-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_artificialsecuritycard_location_ne_assay_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='month',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
