# Generated by Django 4.2.9 on 2024-03-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_assay_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='day',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assay',
            name='year',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
