# Generated by Django 4.2.9 on 2024-03-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_counter_missionlock_remove_depthofexcavation_assay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assay',
            old_name='feeder_num',
            new_name='cable_length',
        ),
        migrations.RenameField(
            model_name='assay',
            old_name='location',
            new_name='depth_of_excavation',
        ),
        migrations.AddField(
            model_name='assay',
            name='fossil_view',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assay',
            name='neighborhood',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assay',
            name='station',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
